# Vectors using Numpy

#### **What is Numpy?**
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

There are several important differences between NumPy arrays and the standard Python sequences(lists):

*   NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
*   The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
*    NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
*    A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. Numpy is preferred due to its performance in computation.



In [1]:
# Lets Import Numpy
import numpy as np

In [2]:
# Define two NumPy arrays
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])

print(n1)
print(n2)

[1 2 3]
[4 5 6]


In [3]:
# Redefine n1 as a 1x3 vector
n1 = np.array([22, 33, 44])

print(n1)

[22 33 44]


#### Addition

Adding numpy vectors is as simple as performing regular addition in Python.

In [4]:
# Subtract vector [2, 3, 4] from n1
result = n1 - np.array([2, 3, 4])
print(result)

[20 30 40]


#### Subtraction

Subtracting numpy vectors is also as simple as performing regular subtraction in Python

In [5]:
# Element-wise multiplication using numpy.multiply
result = np.multiply(n1, np.array([11, 12, 13]))
print(result)

[242 396 572]


#### Scalar Multiplication/ Element-wise multiplication

This is also very easy to perform. Regular Python is enough or numpy also comes with functions to perform the same

https://numpy.org/doc/stable/reference/generated/numpy.multiply.html#numpy-multiply


In [6]:
# Multiply n1 by its transpose
result = np.dot(n1, n1.T)
print(result)

3509


In [7]:
# Create a 3x3 matrix of prime numbers from 1 to 23
v1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23]).reshape(3, 3)

# Find its inverse
v2 = np.linalg.inv(v1)

# Multiply v1 by its inverse and round to remove floating-point noise
identity_matrix = np.round(np.dot(v1, v2), decimals=10)

print(identity_matrix)

[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


#### Vector Multiplication

Vector multiplication, or also called dot product of vectors/matrices. Numpy has functions to perform the same

https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy-dot
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape

note: numpy functions also carry additional features for certain scenarios of inputs. The reference mentions all of them, we will be looking only at our required case here.

In [8]:
# Three different NumPy universal functions on v1
print("Square root:")
print(np.sqrt(v1))

print("Square:")
print(np.square(v1))

print("Sine:")
print(np.sin(v1))

Square root:
[[1.41421356 1.73205081 2.23606798]
 [2.64575131 3.31662479 3.60555128]
 [4.12310563 4.35889894 4.79583152]]
Square:
[[  4   9  25]
 [ 49 121 169]
 [289 361 529]]
Sine:
[[ 0.90929743  0.14112001 -0.95892427]
 [ 0.6569866  -0.99999021  0.42016704]
 [-0.96139749  0.14987721 -0.8462204 ]]


In [9]:
# TASK: perform vector multiplication of n1 and transpose of n1. Use numpy techniques for transpose

# Your Code:




# Expected output: 3059

In [10]:
# TASK: Initialize a vector (v1) with prime numbers 1 to 23, with order 3x3. Initialize a vector (v2) as inverse of v1.
# Perform vector multiplication of both and get identityu matrix. Use numpy rounding methods if needed
# https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html#numpy-linalg-inv
# https://numpy.org/doc/stable/reference/generated/numpy.round.html#numpy-round

# Your Code:





# Expected output (with or without signs both is ok):
# [[ 1., -0.,  0.],
#  [ 0.,  1.,  0.],
#  [-0., -0.,  1.]]

#### Go Through Documentation

https://numpy.org/doc/stable/user/quickstart.html#the-basics

In [11]:
# TASK: Study and perform 3 different universal functions on v1





